[manifest]
version = "1.0.0"
dump_lua = true
priority = 2

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = '''function GameManager:drawExpandedHud()'''
position = "after"
payload = '''
color(cs.vfx.uiColor)

function sectionSkippable()

end

--cs.cBeat


if sectionSkippable() then
    love.graphics.setFont(fonts.digitalDisco)
    love.graphics.setLineWidth(1)

    love.graphics.print("Hold to skip", 3, project.res.y / 2)

    love.graphics.rectangle('line', 3, project.res.y / 2 + 16, 100, 8)
end
'''
match_indent = true