[manifest]
version = "1"
dump_lua = true
priority = 1



# custom wip levels

[[patches]]
[patches.pattern]
target = "states/Menu.lua"
pattern = '''self.mainMenu:addOption('customs',function()'''
position = "before"
payload = '''
if mods.lemontweaks.config.misc.menus.customwiplevels then
    local goToCustomWIPs = function()
		if not love.filesystem.getInfo('Custom WIP Levels','directory') then
			love.filesystem.createDirectory('Custom WIP Levels')
		end

		cs.bg.delete = true
		cs = bs.load('SongSelect')
		self.menuMusicManager:clearOnBeatHooks()

		self:leave()
		cs.menuMusicManager = self.menuMusicManager
		cs.topDirectory = 'Custom WIP Levels/'
		cs.allowEditor = true
		cs:init()
	end

    self.mainMenu:addOption('wipcustoms',function()
		self:checkTutorials(goToCustomWIPs)	
	end, 17, nil, sprites.menu.wipcustoms)
end
'''
match_indent = true



# no discord
[[patches]]
[patches.pattern]
target = "states/Menu.lua"
pattern = '''
self.mainMenu:addOption('discordLink',function()
	love.system.openURL('https://discord.gg/MAXGRYPMSw')
end, 17*7, nil, sprites.menu.discord)
'''
position = "at"
payload = '''
if not mods.lemontweaks.config.misc.menus.nodiscord then
    self.mainMenu:addOption('discordLink',function()
        love.system.openURL('https://discord.gg/MAXGRYPMSw')
    end, 17*7, nil, sprites.menu.discord)
end
'''
match_indent = true