[manifest]
version = "1.0.0"
dump_lua = true
priority = 0



# sfx

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''cs = bs.load(project.initState)'''
position = "after"
payload = '''
local customsfx = {
    { label = "Barely", value = "barely", fallback = "assets/sfx/barely.ogg" },
    { label = "Block", value = "block", fallback = "assets/sfx/click.ogg" },
    { label = "Click", value = "click", fallback = "assets/sfx/click.ogg" },
    { label = "Hold", value = "hold", fallback = "assets/sfx/hold.ogg" },
    { label = "Hover", value = "hover", fallback = "assets/sfx/click.ogg" },
    { label = "Mine", value = "mine", fallback = "assets/sfx/mine.ogg" },
    { label = "Pause", value = "pause", fallback = "assets/sfx/pause.ogg" },
    { label = "Side", value = "side", fallback = "assets/sfx/click.ogg" },
    { label = "Tap", value = "tap", fallback = "assets/sfx/tap.ogg" },
    { label = "Miss", value = "miss", fallback = "assets/sfx/mine.ogg" }
}

local function replaceSounds()
    for i = 1, #customsfx, 1 do
        local audioPath = customsfx[i].fallback

        if mods.lemontweaks.config.customsounds.sfx[customsfx[i].value] ~= "default" and love.filesystem.exists("Mods/lemontweaks/customsounds/sfx/" .. customsfx[i].value .. "/" .. mods.lemontweaks.config.customsounds.sfx[customsfx[i].value]) then
            audioPath = "Mods/lemontweaks/customsounds/sfx/" .. customsfx[i].value .. "/" .. mods.lemontweaks.config.customsounds.sfx[customsfx[i].value]
        end

        if love.filesystem.exists(audioPath) then
            --sounds[customsfx[i].value] = audioPath
            sounds:replaceSound(customsfx[i].value, audioPath)
        end
    end
end

-- run when the game loads
replaceSounds()

-- is this scuffed as shit? probably. does it work? also probably.
local metatable = {
    __newindex = function(table, key, value)
        replaceSounds()
        rawset(table, key, value)
    end
}

setmetatable(mods.lemontweaks.config.customsounds.sfx, metatable)
'''
match_indent = true
